package com.aliyun.emr.ack.cli;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import lombok.Getter;
import lombok.Setter;

/**
 * Parsed Spark submit arguments.
 *
 * <p>A mutable value object the parser fills in field by field. Plain accessors are generated by
 * Lombok ({@code @Getter}/{@code @Setter}); only the few derived/tri-state convenience methods are
 * hand-written below.
 */
@Getter
@Setter
public class SparkSubmitArgs {
    private String name;
    private String className;
    private String resource;
    private String batchType = "SPARK";
    private String proxyUser;
    private String queue;
    private String statusBatchId;
    private String killBatchId;
    private List<String> args = new ArrayList<>();
    private Map<String, String> conf = new HashMap<>();
    private List<String> pyFiles = new ArrayList<>();
    private List<String> files = new ArrayList<>();
    private List<String> jars = new ArrayList<>();
    private List<String> archives = new ArrayList<>();
    private List<String> packages = new ArrayList<>();
    private List<String> repositories = new ArrayList<>();
    private String driverCores;
    private String deployMode;
    private String sqlFile;        // -f: SQL file path
    private String sqlStatement;   // -e: SQL statement string
    private Long timeoutSeconds;   // --timeout: job timeout in seconds
    private boolean sqlSessionMode;  // --session: use session mode for SQL (-e/-f) instead of default batch mode
    private Boolean driverLogStream;         // stream the live Spark driver pod log to the console; null = unset (default on), set by --driver-log/--no-driver-log or config
    private String driverLogGrep;            // --driver-log-grep: only print driver log lines matching this regex
    private String driverLogGrepV;           // --driver-log-grep-v: drop driver log lines matching this regex

    // Kyuubi connection configuration (command-line override)
    private String kyuubiUrl;      // --kyuubi-url: Kyuubi server URL
    private String kyuubiUser;     // --kyuubi-user: Kyuubi username
    private String kyuubiPassword; // --kyuubi-password: Kyuubi password
    private String sparkHistoryUrl; // --history-url: Spark History Server URL
    private String configFile;     // --config-file: custom config file path

    /** Resolved flag: defaults to on when neither the CLI nor the config file set it. */
    public boolean isDriverLogStream() {
        return driverLogStream == null || driverLogStream;
    }

    public boolean isSqlBatchMode() {
        return !sqlSessionMode;
    }

    /** Check if this is a SQL submission mode (-f or -e). */
    public boolean isSqlMode() {
        return sqlFile != null || sqlStatement != null;
    }
}
